### ISSUE TITLE
key won't save

### ISSUE THREAD

**Issue by ngzax** [Fang-/blockio#1]
I believe I have followed the instructions correctly, and my urbit's homepage shows my address:

![screen shot 2017-09-19 at 8 57 54 am](https://user-images.githubusercontent.com/87197/30593488-af41d824-9d18-11e7-8532-f59ff4a99e24.png)

But from the console, when I try to get a balance, it keeps saying that it doesn't have my key:

```
······················ doge > balance
                    !! No API key for DOGE. `key abcd-12...` to set.
                    !! Balance request timed out.
······················ doge > key xxxx-xxxx-xxxx-xxxx
······················ doge > pin ...
: /~doznyl-wanmev-paglyn-simdyr--hindec-hoptyv-dinrux-hadfun/zax/23/sec/io/block/atom
······················ doge > balance
                    !! No API key for DOGE. `key abcd-12...` to set.
                    !! Balance request timed out.
```

The only thing I can see that I did slightly differently, is that I installed this into a different desk (%zax) not %home. Could that possibly be the problem?

**Comment by Fang-** [comment]
Hm, yeah. It neatly _writes_ the sec file to the desk the app's installed in, but blindly tries to _read_ it from the home desk.

Let me see if I can whip up a fix for you real quick.

**Comment by Fang-** [comment]
The commit I made just now should have fixed this for you. Let me know! (:  
(You will need to set key and pin one last time.)

**Comment by ngzax** [comment]
verified that this fixed my issue. Although there *is* an issue with arvo getting confused over apps running in non-home desks, apparently.
